apiVersion: v1
kind: Pod
metadata:
  # namespace: frontend
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.tag }}
  labels:
      app: {{ .Values.deployment.name }}
      version: {{ .Values.deployment.tag }}
spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.deployment.image}}:{{ .Values.deployment.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AUTH_HOST
            value: weatherapp-auth
          - name: AUTH_PORT
            value: "8080"
          - name: WEATHER_HOST
            value: weatherapp-weather
          - name: WEATHER_PORT
            value: "5000"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
